### ISSUE TITLE
Fabric Server won't start when "Souring Phantoms" mod

### ISSUE THREAD

**Issue by cosmichero2025** [Chailotl/sushi-bar#1]
Minecraft Version: 1.20.1
Fabric Server Version: 0.15.11
Sushi Bar Version: 0.2.1+1.20

I'm running a fabric server and when I try to use Sushi Bar with Souring Phantoms the server refuses to start. When I remove Souring Phantoms things start normally. Things work just fine in single player though. I posted an issue on "Souring Phantoms" issues page but I was told that the conflict may be coming from this API mod

Original Issue Post
https://github.com/pajicadvance/soaring-phantoms/issues/1

Souring Phantoms
https://modrinth.com/mod/soaring-phantoms

Server Error Log
[2024-06-21-3.log.gz](https://github.com/user-attachments/files/15937605/2024-06-21-3.log.gz)

Edit: After removing sushi bar from the server side and just leaving it on the client it fixed my issue. Not sure why it didn't like souring phantoms though

**Comment by MrMasrozYTLIVE** [comment]
This issue happens with every single mod that uses Sushi-Bar. I am using `Things` and `sculkhornid` on my server and it crashes due to Sushi-Bar trying to load `class_437` which is `Screen` and it does not exist on a server-side obviously

**Comment by MrMasrozYTLIVE** [comment]
Deleting this mod also helped for me

**Comment by MrMasrozYTLIVE** [comment]
Made PR #2 that should hopefully fix that issue
